### ISSUE TITLE
求开源代码！

### ISSUE THREAD

**Issue by duanyongli** [Lishunkai/CNN-SLAM#1]
你好，请问您有CNN-SLAM的开源代码么？我对这方面也比较感兴趣，想研究研究。

**Comment by Lishunkai** [comment]
Hello,

Sorry, the author of CNN-SLAM didn't put his source code publicly available. And I'm trying to build a CNN-SLAM system according to this paper.

**Comment by yujincheng** [comment]
同学好，看到你也准备复现 CNN-SLAM的工作。我们是清华大学电子系高能效系统实验室。之前在神经网络加速器方面有一些工作，依托实验室之前的技术，也有一家startup，深鉴科技（deephi-tech)。我们准备将神经网络加速器应用到SLAM中，现在也正在复现  CNN-SLAM 的工作，我们准备基于ORB-SLAM2 的开源代码框架进行修改。请问您是基于什么开源框架进行开发的呢？

**Comment by Lishunkai** [comment]
你好，很高兴认识你们团队。
      CNN-SLAM论文本身是用LSD-SLAM开源框架做的，整个论文的优化也是依据LSD-SLAM做的。LSD-SLAM是一种直接法SLAM，ORB-SLAM是特征点法SLAM，两者在实现的原理上有些不同。因此如果用ORB-SLAM做CNN-SLAM的话，可能优化的那几个公式需要改动一下。不过，我也准备用ORB-SLAM2的开源框架做，因为ORB-SLAM2现在的效果是比LSD-SLAM好很多的，而且是以后的趋势。
祝好，
Shunkai Li

**Comment by kaushikray1** [comment]
Did you have any luck replicating the algorithm as mentioned in the paper?

**Comment by UsamaMaq** [comment]
Hello any success in implementing the algorithm according to Tateno's paper?

**Comment by AreteQin** [comment]
您好 请问您成功复现这篇论文了吗，可以和您交流一下吗，我的邮箱是qinqiaomeng@163.com
